# Generated by Django 2.0.5 on 2018-06-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_auto_20180619_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactsModel',
        ),
    ]
