# Generated by Django 2.0.5 on 2018-06-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_auto_20180620_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsmodel',
            name='what_about',
        ),
    ]
